import type { FastifyBaseLogger } from "fastify";
import { updateSession } from "./updateSession";

/**
 * Store the CLI-generated session ID
 *
 * Non-critical operation that stores the session ID generated by the CLI
 * for session resumption. Logs warnings on failure but doesn't throw.
 *
 * @param sessionId - The database session ID
 * @param cliSessionId - The CLI-generated session ID (optional)
 * @param logger - Optional logger instance
 */
export async function storeCliSessionId(
  sessionId: string,
  cliSessionId: string | undefined,
  logger?: FastifyBaseLogger
): Promise<void> {
  if (!cliSessionId) {
    return;
  }

  try {
    logger?.info(
      { sessionId, cliSessionId },
      "Storing CLI-generated session ID"
    );

    await updateSession(
      sessionId,
      { cli_session_id: cliSessionId },
      false // Don't broadcast - non-critical metadata update
    );
  } catch (err: unknown) {
    // Non-critical error - log and continue
    logger?.warn(
      { err, sessionId },
      "Failed to store CLI session ID (non-critical)"
    );
  }
}
