// Auto-generated by workflow-sdk generate-slash-types
// Do not edit this file manually

/**
 * Union type of all available slash command names
 */
export type SlashCommandName = "/audit" | "/check" | "/commit-and-push" | "/commit" | "/document-cli-tool" | "/find-claude-session" | "/fix" | "/generate-feature" | "/generate-prd" | "/generate-research" | "/generate-slash-command" | "/generate-spec-simple" | "/implement-spec" | "/list-specs" | "/move-spec" | "/prime" | "/pull-request" | "/review-spec-implementation" | "/tools" | "/use-browser";

/**
 * Mapping of command names to their argument types
 */
export interface SlashCommandArgs {
  "/audit": { "mode": string; "scope": string };
  "/check": { "format": string };
  "/commit-and-push": { "base-branch": string };
  "/commit": Record<string, never>;
  "/document-cli-tool": { "cli-name": string };
  "/find-claude-session": { "search-description": string; "project-path (optional)": string };
  "/fix": Record<string, never>;
  "/generate-feature": { "featureName": string; "context": string; "format": string };
  "/generate-prd": { "featurename": string; "context": string; "format": string };
  "/generate-research": { "featureName": string; "researchTopic": string; "format": string };
  "/generate-slash-command": { "command-name": string; "description": string };
  "/generate-spec-simple": { "number-or-feature-name": string; "format": string };
  "/implement-spec": { "specNumberOrNameOrPath": string; "format": string };
  "/list-specs": { "folder": string; "status": string };
  "/move-spec": { "specNumberOrNameOrPath": string; "targetFolder": string };
  "/prime": Record<string, never>;
  "/pull-request": { "title": string; "format": string };
  "/review-spec-implementation": { "specNumberOrNameOrPath": string; "format": string };
  "/tools": Record<string, never>;
  "/use-browser": { "featureSteps": string };
}

/**
 * Build a type-safe slash command string
 *
 * @param name - Command name (e.g., "/generate-prd")
 * @param args - Command arguments object
 * @returns Formatted command string with escaped quotes
 *
 * @example
 * buildSlashCommand("/generate-prd", { featureName: "auth", context: "Add OAuth" })
 * // Returns: "/generate-prd 'auth' 'Add OAuth'"
 */
export function buildSlashCommand<T extends SlashCommandName>(
  name: T,
  args: SlashCommandArgs[T]
): string {
  const parts: string[] = [name];

  // Add arguments in order (if any)
  if (args && typeof args === "object") {
    for (const value of Object.values(args)) {
      // Skip undefined values (optional arguments)
      if (value !== undefined && value !== null) {
        // Escape single quotes in the value
        const escaped = String(value).replace(/'/g, "\\'");
        parts.push(`'${escaped}'`);
      }
    }
  }

  return parts.join(" ");
}

